openapi: 3.0.0
info:
  title: Country API
  description: API for managing country information
  version: 1.0.0
  contact:
    name: Ridwan Ajayi Olalekan
    email: ridwanullahiajayi01@gmail.com
    url: 'https://github.com/yourgithubusername'
servers:
  - url: https://countriesapi-production-3385.up.railway.app
paths:
  /countries:
    get:
      summary: Get all countries
      responses:
        '200':
          description: A list of countries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'
    post:
      summary: Create a new country
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Country'
      responses:
        '201':
          description: Country created successfully
    delete:
      summary: Delete all countries
      responses:
        '204':
          description: Countries deleted successfully
  /countries/{country_code}:
    parameters:
      - in: path
        name: country_code
        required: true
        description: ISO 3166-1 alpha-2 country code
        schema:
          type: string
    get:
      summary: Get country by country code
      responses:
        '200':
          description: Country information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
    put:
      summary: Update country by country code
      parameters:
        - in: path
          name: country_code
          required: true
          description: ISO 3166-1 alpha-2 country code
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Country'
      responses:
        '200':
          description: Country updated successfully
    delete:
      summary: Delete country by country code
      responses:
        '204':
          description: Country deleted successfully
components:
  schemas:
    Country:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        alpha2Code:
          type: string
        alpha3Code:
          type: string
        capital:
          type: string
        population:
          type: integer
        region:
          type: string
        subregion:
          type: string
        area:
          type: integer
        flag:
          type: string
        timezones:
          type: string
        borders:
          type: string
        currencies:
          type: string
        government:
          type: string
        gdp:
          type: string
        language:
          type: string
        officialLanguage:
          type: string
        climate:
          type: string
        terrain:
          type: string
        populationDensity:
          type: number
        governmentType:
          type: string
        officialCurrency:
          type: string
        nationalAnimal:
          type: string
        nationalSport:
          type: string
